# Sử dụng hình ảnh Python chính thức
FROM python:3.9-slim

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Copy tệp requirements.txt vào container
COPY requirements.txt /app/

# Cài đặt các thư viện cần thiết từ requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy mã nguồn và thư mục templates vào trong container
COPY . /app/

# Mở cổng 5000
EXPOSE 5000

# Lệnh để chạy ứng dụng Flask
CMD ["python", "app.py"]
