
FROM python:3.9-slim
WORKDIR /app

# Copy tệp requirements.txt vào container
COPY requirements.txt /app/

# Cài đặt các thư viện cần thiết từ requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy mã nguồn vào trong container
COPY . /app/

# Mở cổng 5000
EXPOSE 5000

# Lệnh để chạy ứng dụng Flask
CMD ["python", "app.py"]
